### ISSUE TITLE
Fix update_fw.py

### ISSUE THREAD

**Issue by encryptize** [Encryptize/scooterflasher#3]
`update_firmware()` function requires data from API response to work.

**Comment by BastelPichi** [comment]
Cant we just get rid of this entirely? Scooterflasher prompts and downloads the files (if you allow it to) on its own.

**Comment by encryptize** [comment]
> Cant we just get rid of this entirely? Scooterflasher prompts and downloads the files (if you allow it to) on its own.

That's right. Removed. https://github.com/Encryptize/scooterflasher/commit/8d2a5d7989bc75795e78c1d79064a7d80915482c
